# @package _global_

Training:
  device: cuda
  gpus: [0, 1]
  max_epochs: 9999
  val_check_interval: 1.0
  limit_val_batches: 100
  pretrain_g_only: true
  g_pretrain_steps: 5000
  adv_loss_ramp_steps: 500
  label_smoothing: true
  EMA:
    enabled: false
    decay: 0.999
    update_after_step: 0
    use_num_updates: true
  Losses:
    adv_loss_type: bce
    relativistic_average_d: false
    adv_loss_beta: 0.001
    adv_loss_schedule: cosine
    r1_gamma: 0.0
    l1_weight: 1.0
    sam_weight: 0.00
    perceptual_weight: 0.05
    perceptual_metric: vgg
    fixed_idx: [0, 1, 2]
    tv_weight: 0.0
    max_val: 1.0
    ssim_win: 11

Optimizers:
  optim_g_lr: 1e-5
  optim_d_lr: 5e-5
  gradient_clip_val: 0
  betas: [0.0, 0.99]
  eps: 1.0e-7
  weight_decay_g: 0.0
  weight_decay_d: 0.0

Schedulers:
  g_warmup_steps: 0
  g_warmup_type: linear
  metric_g: val_metrics/l1
  metric_d: validation/DISC_adversarial_loss
  patience_g: 10
  patience_d: 10
  factor_g: 0.5
  factor_d: 0.5
